version: "3.3"
services:
  tomcat:
    image: tomcat:latest
    ports:
      - "8080:8080"
      - "8000:8000" # used for debug
    environment:
      # start tomcat catalina on debug mode 
      CATALINA_OPTS: -agentlib:jdwp=transport=dt_socket,address=8000,server=y,suspend=n
    volumes:
      - ./src/main/webapp:/usr/local/tomcat/webapps/ROOT
      - ./target/arquivo-webapp/WEB-INF/classes:/usr/local/tomcat/webapps/ROOT/WEB-INF/classes
      - ./target/arquivo-webapp/WEB-INF/lib:/usr/local/tomcat/webapps/ROOT/WEB-INF/lib
      - ./src/development/tomcat/conf/server.xml:/usr/local/tomcat/conf/server.xml
