Content = {
    months: 
		{ 	 '01': "January",
			 '02': "February",
			 '03': "March",
			 '04': "April",
			 '05': "May",
			 '06': "June",
			 '07': "July",
			 '08': "August",
			 '09': "September",
			 '10': "October",
			 '11': "November",
			 '12': "December",
		},
    months_alt: 
        {    '01': "January",
             '02': "February",
             '03': "March",
             '04': "April",
             '05': "May",
             '06': "June",
             '07': "July",
             '08': "August",
             '09': "September",
             '10': "October",
             '11': "November",
             '12': "December",
        },
    shortMonths: 
		{ 	 '01': "Jan",
			 '02': "Feb",
			 '03': "Mar",
			 '04': "Apr",
			 '05': "May",
			 '06': "Jun",
			 '07': "Jul",
			 '08': "Aug",
			 '09': "Sep",
			 '10': "Oct",
			 '11': "Nov",
			 '12': "Dez",
		},
    savedInArchive:"We archived",
    versionsStored:"Versions table",
    versionsPage:"versions of",
    between:"between",
    and:"and",
    resultsQuestion:"Did you want to see webpages with the text:",
    moreOptions:"More options",
    lessOptions:"Less options",
    help:"Help",
    helpHref:"http://sobre.arquivo.pt/help/faq?set_language=en",
    newSearch:"New search",
    at:"at",
    shareMessage:"Arquivo.pt: search pages from the past.",
    language:"en",
    otherDates:"Versions table",
    emailMessage:"Interesting Web Page from the Past &body=",
    noResultsFound:"No results were found for the query:",
    suggestions:"We suggest that you:",
    checkSpelling:"Verify the URL.",
    differentKeywords:"Try different keywords.",
    generalWords:"Try more general words.",
    internetArchive:"Search the",
    suggestSiteArchived:"the site to be archived.", 
    suggestUrl:"https://arquivo.pt/suggest?your-sites=",
    suggest:"Suggest", 
    mementoFind:"Search other web archives",
    embargo:"Embargo",
    embargoUrl:"http://sobre.arquivo.pt/help/access-to-archived-contents#section-6",
    notArchived:"Not Archived",
    otherLanguage: "PT",
    preservedByArquivo: " - preserved by Arquivo.pt",
    searchVersion: "version",
    searchVersions: "versions",
    table: "Table",
    list: "List",

    datepicker: {
        error: {
            date: "Start date cannot be higher than end date."
        }
    },
    picker: {
        ok: "OK",
        cancel: "Cancel",
        start: {
            header: "From",
        },
        end: {
            header: "Until",
        },
    },
    images: {
        details: {
            details: "Details",
            page: "Page",
            title: "title:",
            image: "Image",
            resolution: "resolution:",
            safesearch: "safesearch score:",
            collection: "Collection",
            name: "name:",
        },
        viewer: {
            visit: "Visit",
        },
    }, 
    search: {
        noResults: {
            title: "No results were found for the query:",
            suggestions: {
                intro : "We suggest that you:",
                wellWritten: "Make sure all words are spelled correctly.",
                timeInterval: "Widen the time interval of your query.",
                keywords: "Try different keywords.",
                genericWords: "Try more general words.",
            },
        },
        viewMoreForSameSite: "View more results of",
    },
    topbar: {
        help: "Help",
        about: "About",
        portuguese: "Portugu&ecirc;s",
        english: "English",
        aboutUrl: "//sobre.arquivo.pt/en/",
        OtherLanguage: "Portugu&ecirc;s",
        OtherLanguageShort: "pt",
        otherLanguage: "Pt",
        link: {
            copied: "Link copied",
        },
        menu: {
            home: "New search",
            advanced: "Advanced search",
            share: "Share",
            about: "About",
            otherLanguage: "Portugu&ecirc;s",
            desktop: "Desktop version",
            images: "Image search",
            bug: "https://sobre.arquivo.pt/en/contact/?your-subject=Problem%20in%20arquivo.pt&your-message=",
            report: "Report a bug",
            pages: "Pages",
            copy: "Copy link",
            images: "Images",
        },
        optionsMenu: {
            exportSERPCSV: "Export results (CSV)",
            exportSERPXLSX: "Export results (XLSX)",
            exportSERPTXT: "Exportar results (TXT)",
        },
    },
    header: {
        menu: "Menu",
        options: "Options",
    },
    exportSERP: {
        pageSearch: {
            queryArgument: "Argument",
            queryValue: "Value",
            query: "Query search",
            from: "From",
            to: "To",
            offset: "Offset",
            maxItems: "Number of results",
            siteSearch: "Website",
            type: "Format",
            collection: "Collection",
            results: "Results",
            year: "Year",
            month: "Month",
            day: "Day",
            timestamp: "Timestamp",
            originalURL: "Original URL",
            linkToArchive: "Link to archive",
            linkToScreenshot: "Link to screenshot",
            linkToExtractedText: "Link to extracted text",
            mimeType: "MIME type",
            title: "Title",
            snippet: "Snippet",
        },
        imageSearch: {
            queryArgument: "Argument",
            queryValue: "Value",
            query: "Query search",
            from: "From",
            to: "To",
            offset: "Offset",
            maxItems: "Number of results",
            siteSearch: "Website",
            type: "Format",
            collection: "Collection",
            year: "Year",
            month: "Mês",
            day: "Day",
            imgTstamp: "Image timestamp",
            imgHeight: "Image height",
            imgWidth: "Image width",
            imgSrc: "Image source link",
            imgLinkToArchive: "Image link to archive",
            collection: "Collection",
            imgMimeType: "Image MIME type",
            imgAlt: "Image alt",
            imgTitle: "Image title",
            pageTstamp: "Page timestamp",
            pageURL: "Page URL that references the image",
            pageLinkToArchive: "Page link to archive",
            pageTitle: "Page title",
        }
    },
    pageSearchButton: "Pages",
    imageSearchButton: "Images",
};
