Content = {
    months: 
		{ 	 '01': "Janeiro",
			 '02': "Fevereiro",
			 '03': "Março",
			 '04': "Abril",
			 '05': "Maio",
			 '06': "Junho",
			 '07': "Julho",
			 '08': "Agosto",
			 '09': "Setembro",
			 '10': "Outubro",
			 '11': "Novembro",
			 '12': "Dezembro",
		},
    months_alt: 
        {    '01': "Janeiro",
             '02': "Fevereiro",
             '03': "Mar&#231;o",
             '04': "Abril",
             '05': "Maio",
             '06': "Junho",
             '07': "Julho",
             '08': "Agosto",
             '09': "Setembro",
             '10': "Outubro",
             '11': "Novembro",
             '12': "Dezembro",
        },
    shortMonths: 
		{ 	 '01': "Jan",
			 '02': "Fev",
			 '03': "Mar",
			 '04': "Abr",
			 '05': "Mai",
			 '06': "Jun",
			 '07': "Jul",
			 '08': "Ago",
			 '09': "Set",
			 '10': "Out",
			 '11': "Nov",
			 '12': "Dez",
		},
    savedInArchive:"Foram gravadas no arquivo",
    versionsStored:"Tabela de vers&#245;es",
    versionsPage:"vers&#245;es de",
    between:"entre",
    and:"e",
    resultsQuestion:"Pretendia ver os resultados das p&#225;ginas que cont&#234;m o texto:",
    moreOptions:"Mais op&#231;&#245;es",
    lessOptions:"Menos op&#231;&#245;es",
    help:"Ajuda",
    helpHref:"http://sobre.arquivo.pt/ajuda",
    newSearch:"Nova pesquisa",
    at:"&#224;s",
    shareMessage:"Arquivo.pt",
    language:"pt",
    otherDates:"Tabela de vers&#245;es",
    emailMessage:"Pagina Interessante Do Passado &body=",
    noResultsFound:"N&#227;o foram encontrados resultados para a sua pesquisa:",
    suggestions:"Sugerimos que:",
    checkSpelling:"Verifique o URL",
    differentKeywords:"Tente utilizar outras palavras-chave.",
    generalWords:"Tente palavras mais gerais.", 
    internetArchive:"Pesquise no",
    suggestSiteArchived:"a p&#225gina para que seja arquivada.",
    suggestUrl:"https://arquivo.pt/sugerir?your-sites=",
    suggest:"Sugira", 
    mementoFind:"Pesquise outros arquivos web",
    embargo:"Embargo",
    embargoUrl:"http://sobre.arquivo.pt/ajuda/acesso-a-conteudos-arquivados#section-6",
    notArchived:"N&#227;o Arquivado",
    otherLanguage: "EN",
    preservedByArquivo: " - preservado pelo Arquivo.pt",
    searchVersion: "vers&atilde;o",
    searchVersions: "vers&otilde;es",
    table: "Tabela",
    list: "Lista",

    datepicker: {
        error: {
            date: "A data inicial n&atilde;o pode ser superior<br /> a data final.",
        },
    },
    picker: {
        ok: "OK",
        cancel: "Cancelar",
        start: {
            header: "A partir de:",
        },
        end: {
            header: "At&eacute;:",
        },
    },
    images: {
        details: {
            details: "Detalhes",
            page: "P&aacute;gina",
            title: "t&iacute;tulo:",
            image: "Imagem",
            resolution: "resolu&ccedil;&atilde;o:",
            safesearch: "classifica&ccedil;&atilde;o safesearch:",
            collection: "Cole&ccedil;&atilde;o",
            name: "nome:",
        },
        viewer: {
            visit: "Visitar",
        },
    }, 
    search: {
        noResults: {
            title: "N&atilde;o foram encontrados resultados para a sua pesquisa:",
            suggestions: {
                intro: "Sugerimos que:",
                timeInterval: "Aumente o intervalo de tempo",
                genericWords: "Pesquise outras palavras",
                advancedSearch: "Experimente a <a href=\"javascript:void(0)\" onclick=\"$('#advancedSearchButton').click();\">Pesquisa avan&ccedil;ada</a>",
            },
        },
        viewMoreForSameSite: "Ver mais resultados de",
    },
    topbar: {
        help: "Ajuda",
        about: "Sobre",
        portuguese: "Portugu&ecirc;s",
        english: "English",
        aboutUrl: "//sobre.arquivo.pt/pt/",
        OtherLanguage: "English",
        OtherLanguageShort: "en",
        otherLanguage: "En",
        link: {
            copied: "Link copiado",
        },
        menu: {
            home: "Nova pesquisa",
            advanced: "Pesquisa avan&ccedil;ada",
            share: "Partilhar",
            about: "Sobre",
            otherLanguage: "English",
            desktop: "Vers&atilde;o desktop",
            images: "Pesquisa de imagens",
            bug: "https://sobre.arquivo.pt/pt/contacto/?your-subject=Problema%20no%20arquivo.pt&your-message=",
            report: "Reportar problema",
            pages: "P&aacute;ginas",
            copy: "Copiar link",
            images: "Imagens",
        },
        optionsMenu: {
            exportSERPCSV: "Exportar resultados (CSV)",
            exportSERPXLSX: "Exportar resultados (XLSX)",
            exportSERPODS: "Exportar resultados (ODS)",
            exportSERPTXT: "Exportar resultados (TXT)",
        },
    },
    header: {
        menu: "Menu",
        options: "Op&ccedil;&otilde;es",
    },
    exportSERP: {
        pageSearch: {
            queryArgument: "Argumento",
            queryValue: "Valor",
            query: "Termos de pesquisa",
            from: "De",
            to: "Até",
            offset: "Resultado a partir de",
            maxItems: "Número de resultados",
            siteSearch: "Sítio web",
            type: "Formato",
            collection: "Coleção",
            results: "Resultados",
            year: "Ano",
            month: "Mês",
            day: "Dia",
            timestamp: "Carimbo de tempo",
            originalURL: "URL original",
            linkToArchive: "Link para versão arquivada",
            linkToScreenshot: "Link para captura de ecrã",
            linkToExtractedText: "Link para texto extraído",
            mimeType: "Tipo de mídia",
            title: "Título",
            snippet: "Resumo",
        },
        imageSearch: {
            queryArgument: "Argumento",
            queryValue: "Valor",
            query: "Query search terms",
            from: "De",
            to: "Até",
            offset: "Resultado a partir de",
            maxItems: "Número de resultados",
            siteSearch: "Sítio web",
            type: "Formato",
            collection: "Coleção",
            year: "Ano",
            month: "Mês",
            day: "Dia",
            imgTstamp: "Carimbo de tempo da imagem",
            imgHeight: "Altura da imagem",
            imgWidth: "Largura da imagem",
            imgSrc: "Link original da imagem",
            imgLinkToArchive: "Link da imagem arquivada",
            collection: "Coleção",
            imgMimeType: "Tipo de mídia da imagem",
            imgAlt: "Texto alternativo descritivo da imagem",
            imgTitle: "Título da imagem",
            pageTstamp: "Carimbo de tempo da página",
            pageURL: "URL da página",
            pageLinkToArchive: "Link da página arquivada",
            pageTitle: "Título da página",
        }
    },
    pageSearchButton: "P&aacute;ginas",
    imageSearchButton: "Imagens",
    contameHistoriasButton: "Narrativa Temporal",
    leavingArquivoToSearchContameHistorias: "Vai sair do Arquivo.pt para o servi&ccedil;o contamehistorias.pt",
    cancel: "Cancelar",
};
