Content = {
    months: 
		{ 	 '01': "Janeiro",
			 '02': "Fevereiro",
			 '03': "Mar&#231;o",
			 '04': "Abril",
			 '05': "Maio",
			 '06': "Junho",
			 '07': "Julho",
			 '08': "Agosto",
			 '09': "Setembro",
			 '10': "Outubro",
			 '11': "Novembro",
			 '12': "Dezembro",
		},
    shortMonths: 
		{ 	 '01': "jan",
			 '02': "fev",
			 '03': "mar",
			 '04': "abr",
			 '05': "mai",
			 '06': "jun",
			 '07': "jul",
			 '08': "ago",
			 '09': "set",
			 '10': "out",
			 '11': "nov",
			 '12': "dez",
		},
    savedInArchive:"Foram gravadas no arquivo",
    versionsStored:"Tabela de vers&#245;es",
    versionsPage:"vers&#245;es de",
    between:"entre",
    and:"e",
    resultsQuestion:"Pretendia ver os resultados das p&#225;ginas que cont&#234;m o texto:",
    moreOptions:"Mais op&#231;&#245;es",
    lessOptions:"Menos op&#231;&#245;es",
    help:"Ajuda",
    helpHref:"http://sobre.arquivo.pt/ajuda",
    newSearch:"Nova pesquisa",
    at:"&#224;s",
    shareMessage:"Arquivo.pt",
    language:"pt",
    otherDates:"Tabela de vers&#245;es",
    emailMessage:"Pagina Interessante Do Passado &body=",
    noResultsFound:"N&#227;o foram encontrados resultados para a sua pesquisa:",
    suggestions:"Sugerimos que:",
    checkSpelling:"Verifique o URL",
    differentKeywords:"Tente utilizar outras palavras-chave.",
    generalWords:"Tente palavras mais gerais.", 
    internetArchive:"Pesquise no",
    suggestSiteArchived:"a p&#225gina para que seja arquivada.",
    suggestUrl:"https://arquivo.pt/sugerir?your-sites=",
    suggest:"Sugira", 
    mementoFind:"Pesquise outros arquivos web",
    embargo:"Embargo",
    embargoUrl:"http://sobre.arquivo.pt/ajuda/acesso-a-conteudos-arquivados#section-6",
    notArchived:"N&#227;o Arquivado",
    otherLanguage: "EN",
    preservedByArquivo: " - preservado pelo Arquivo.pt",
    searchVersion: "vers&atilde;o",
    searchVersions: "vers&otilde;es",
    table: "Tabela",
    list: "Lista",

    datepicker: {
        error: {
            date: "A data inicial n&atilde;o pode ser superior<br /> a data final.",
        },
    },
    picker: {
        ok: "OK",
        cancel: "Cancelar",
    },
};
